# should take in a message and return the same message but encrypted as well as the key used
# create a function called encryption that takes in a string, and using a random key generated by
# using os.random() with a max range of 255 and the extended ascii table should encrypt the message and return
# the cipher text and the key inside of a file in the same location as the encryption.py file
